const genuineZones = new Map([
  ["phanauet channel", 1],
  ["carpenters' landing", 2],
  ["manaclipper", 3],
  ["bibiki bay", 4],
  ["uleguerand range", 5],
  ["bearclaw pinnacle", 6],
  ["attohwa chasm", 7],
  ["boneyard gully", 8],
  ["pso'xja", 9],
  ["the shrouded maw", 10],
  ["oldton movalpolos", 11],
  ["newton movalpolos", 12],
  ["mine shaft #2716", 13],
  ["hall of transference", 14],
  ["abyssea - konschtat", 15],
  ["promyvion - holla", 16],
  ["spire of holla", 17],
  ["promyvion - dem", 18],
  ["spire of dem", 19],
  ["promyvion - mea", 20],
  ["spire of mea", 21],
  ["promyvion - vahzl", 22],
  ["spire of vahzl", 23],
  ["lufaise meadows", 24],
  ["misareaux coast", 25],
  ["tavnazian safehold", 26],
  ["phomiuna aqueducts", 27],
  ["sacrarium", 28],
  ["riverne - site #b01", 29],
  ["riverne - site #a01", 30],
  ["monarch linn", 31],
  ["sealion's den", 32],
  ["al'taieu", 33],
  ["grand palace of hu'xzoi", 34],
  ["the garden of ru'hmet", 35],
  ["empyreal paradox", 36],
  ["temenos", 37],
  ["apollyon", 38],
  ["dynamis - valkurm", 39],
  ["dynamis - buburimu", 40],
  ["dynamis - qufim", 41],
  ["dynamis - tavnazia", 42],
  ["diorama abdhaljs-ghelsba", 43],
  ["abdhaljs isle-purgonorgo", 44],
  ["abyssea - tahrongi", 45],
  ["open sea route to al zahbi", 46],
  ["open sea route to mhaura", 47],
  ["al zahbi", 48],
  ["aht urhgan whitegate", 50],
  ["wajaom woodlands", 51],
  ["bhaflau thickets", 52],
  ["nashmau", 53],
  ["arrapago reef", 54],
  ["ilrusi atoll", 55],
  ["periqia", 56],
  ["talacca cove", 57],
  ["silver sea route to nashmau", 58],
  ["silver sea route to al zahbi", 59],
  ["the ashu talif", 60],
  ["mount zhayolm", 61],
  ["halvung", 62],
  ["lebros cavern", 63],
  ["navukgo execution chamber", 64],
  ["mamook", 65],
  ["mamool ja training grounds", 66],
  ["jade sepulcher", 67],
  ["aydeewa subterrane", 68],
  ["leujaoam sanctum", 69],
  ["chocobo circuit", 70],
  ["the colosseum", 71],
  ["alzadaal undersea ruins", 72],
  ["zhayolm remnants", 73],
  ["arrapago remnants", 74],
  ["bhaflau remnants", 75],
  ["silver sea remnants", 76],
  ["nyzul isle", 77],
  ["hazhalm testing grounds", 78],
  ["caedarva mire", 79],
  ["southern san d'oria [s]", 80],
  ["east ronfaure [s]", 81],
  ["jugner forest [s]", 82],
  ["vunkerl inlet [s]", 83],
  ["batallia downs [s]", 84],
  ["la vaule [s]", 85],
  ["everbloom hollow", 86],
  ["bastok markets [s]", 87],
  ["north gustaberg [s]", 88],
  ["grauberg [s]", 89],
  ["pashhow marshlands [s]", 90],
  ["rolanberry fields [s]", 91],
  ["beadeaux [s]", 92],
  ["ruhotz silvermines", 93],
  ["windurst waters [s]", 94],
  ["west sarutabaruta [s]", 95],
  ["fort karugo-narugo [s]", 96],
  ["meriphataud mountains [s]", 97],
  ["sauromugue champaign [s]", 98],
  ["castle oztroja [s]", 99],
  ["west ronfaure", 100],
  ["east ronfaure", 101],
  ["la theine plateau", 102],
  ["valkurm dunes", 103],
  ["jugner forest", 104],
  ["batallia downs", 105],
  ["north gustaberg", 106],
  ["south gustaberg", 107],
  ["konschtat highlands", 108],
  ["pashhow marshlands", 109],
  ["rolanberry fields", 110],
  ["beaucedine glacier", 111],
  ["xarcabard", 112],
  ["cape teriggan", 113],
  ["eastern altepa desert", 114],
  ["west sarutabaruta", 115],
  ["east sarutabaruta", 116],
  ["tahrongi canyon", 117],
  ["buburimu peninsula", 118],
  ["meriphataud mountains", 119],
  ["sauromugue champaign", 120],
  ["the sanctuary of zi'tah", 121],
  ["ro'maeve", 122],
  ["yuhtunga jungle", 123],
  ["yhoator jungle", 124],
  ["western altepa desert", 125],
  ["qufim island", 126],
  ["behemoth's dominion", 127],
  ["valley of sorrows", 128],
  ["ghoyu's reverie", 129],
  ["ru'aun gardens", 130],
  ["mordion gaol", 131],
  ["abyssea - la theine", 132],
  ["outer ra'kaznar [u2]", 133],
  ["dynamis - beaucedine", 134],
  ["dynamis - xarcabard", 135],
  ["beaucedine glacier [s]", 136],
  ["xarcabard [s]", 137],
  ["castle zvahl baileys [s]", 138],
  ["horlais peak", 139],
  ["ghelsba outpost", 140],
  ["fort ghelsba", 141],
  ["yughott grotto", 142],
  ["palborough mines", 143],
  ["waughroon shrine", 144],
  ["giddeus", 145],
  ["balga's dais", 146],
  ["beadeaux", 147],
  ["qulun dome", 148],
  ["davoi", 149],
  ["monastic cavern", 150],
  ["castle oztroja", 151],
  ["altar room", 152],
  ["the boyahda tree", 153],
  ["dragon's aery", 154],
  ["castle zvahl keep [s]", 155],
  ["throne room [s]", 156],
  ["middle delkfutt's tower", 157],
  ["upper delkfutt's tower", 158],
  ["temple of uggalepih", 159],
  ["den of rancor", 160],
  ["castle zvahl baileys", 161],
  ["castle zvahl keep", 162],
  ["sacrificial chamber", 163],
  ["garlaige citadel [s]", 164],
  ["throne room", 165],
  ["ranguemont pass", 166],
  ["bostaunieux oubliette", 167],
  ["chamber of oracles", 168],
  ["toraimarai canal", 169],
  ["full moon fountain", 170],
  ["crawlers' nest [s]", 171],
  ["zeruhn mines", 172],
  ["korroloka tunnel", 173],
  ["kuftal tunnel", 174],
  ["the eldieme necropolis [s]", 175],
  ["sea serpent grotto", 176],
  ["ve'lugannon palace", 177],
  ["the shrine of ru'avitau", 178],
  ["stellar fulcrum", 179],
  ["la'loff amphitheater", 180],
  ["the celestial nexus", 181],
  ["walk of echoes", 182],
  ["maquette abdhaljs-legiona", 183],
  ["lower delkfutt's tower", 184],
  ["dynamis - san d'oria", 185],
  ["dynamis - bastok", 186],
  ["dynamis - windurst", 187],
  ["dynamis - jeuno", 188],
  ["king ranperre's tomb", 190],
  ["dangruf wadi", 191],
  ["inner horutoto ruins", 192],
  ["ordelle's caves", 193],
  ["outer horutoto ruins", 194],
  ["the eldieme necropolis", 195],
  ["gusgen mines", 196],
  ["crawlers' nest", 197],
  ["maze of shakhrami", 198],
  ["garlaige citadel", 200],
  ["cloister of gales", 201],
  ["cloister of storms", 202],
  ["cloister of frost", 203],
  ["fei'yin", 204],
  ["ifrit's cauldron", 205],
  ["qu'bia arena", 206],
  ["cloister of flames", 207],
  ["quicksand caves", 208],
  ["cloister of tremors", 209],
  ["cloister of tides", 211],
  ["gustav tunnel", 212],
  ["labyrinth of onzozo", 213],
  ["abyssea - attohwa", 215],
  ["abyssea - misareaux", 216],
  ["abyssea - vunkerl", 217],
  ["abyssea - altepa", 218],
  ["ship bound for selbina", 220],
  ["ship bound for mhaura", 221],
  ["provenance", 222],
  ["san d'oria-jeuno airship", 223],
  ["bastok-jeuno airship", 224],
  ["windurst-jeuno airship", 225],
  ["kazham-jeuno airship", 226],
  ["ship bound for selbina (duplicate)", 227],
  ["ship bound for mhaura (duplicate)", 228],
  ["throne room [v]", 229],
  ["southern san d'oria", 230],
  ["northern san d'oria", 231],
  ["port san d'oria", 232],
  ["chateau d'oraguille", 233],
  ["bastok mines", 234],
  ["bastok markets", 235],
  ["port bastok", 236],
  ["metalworks", 237],
  ["windurst waters", 238],
  ["windurst walls", 239],
  ["port windurst", 240],
  ["windurst woods", 241],
  ["heavens tower", 242],
  ["ru'lude gardens", 243],
  ["upper jeuno", 244],
  ["lower jeuno", 245],
  ["port jeuno", 246],
  ["rabao", 247],
  ["selbina", 248],
  ["mhaura", 249],
  ["kazham", 250],
  ["hall of the gods", 251],
  ["norg", 252],
  ["abyssea - uleguerand", 253],
  ["abyssea - grauberg", 254],
  ["abyssea - empyreal paradox", 255],
  ["western adoulin", 256],
  ["eastern adoulin", 257],
  ["rala waterways", 258],
  ["rala waterways [u]", 259],
  ["yahse hunting grounds", 260],
  ["ceizak battlegrounds", 261],
  ["foret de hennetiel", 262],
  ["yorcia weald", 263],
  ["yorcia weald [u]", 264],
  ["morimar basalt fields", 265],
  ["marjami ravine", 266],
  ["kamihr drifts", 267],
  ["sih gates", 268],
  ["moh gates", 269],
  ["cirdas caverns", 270],
  ["cirdas caverns [u]", 271],
  ["dho gates", 272],
  ["woh gates", 273],
  ["outer ra'kaznar", 274],
  ["outer ra'kaznar [u1]", 275],
  ["ra'kaznar inner court", 276],
  ["ra'kaznar turris", 277],
  ["walk of echoes [p2]", 279],
  ["mog garden", 280],
  ["leafallia", 281],
  ["mount kamihr", 282],
  ["silver knife", 283],
  ["celennia memorial library", 284],
  ["feretory", 285],
  ["maquette abdhaljs-legionb", 287],
  ["escha - zi'tah", 288],
  ["escha - ru'aun", 289],
  ["desuetia - empyreal paradox", 290],
  ["reisenjima", 291],
  ["reisenjima henge", 292],
  ["reisenjima sanctorium", 293],
  ["dynamis - san d'oria [d]", 294],
  ["dynamis - bastok [d]", 295],
  ["dynamis - windurst [d]", 296],
  ["dynamis - jeuno [d]", 297],
  ["walk of echoes [p1]", 298],
]);

const aliasZones = new Map([
  [
    "aht urhgan mission 15: the black coffin|the black coffin",
    genuineZones.get("arrapago reef"),
  ],
  [
    "aht urhgan mission 42: path of darkness|path of darkness",
    genuineZones.get("nyzul isle"),
  ],
  [
    "aht urhgan mission 44: nashmeira's plea|nashmeira's plea",
    genuineZones.get("nyzul isle"),
  ],
  ["an affable adamantking?", genuineZones.get("qulun dome")],
  ["apkallu breeding", genuineZones.get("lebros cavern")],
  ["apkallu seizure", genuineZones.get("ilrusi atoll")],
  ["azure ailments", genuineZones.get("mamool ja training grounds")],
  [
    "azure ailments|azure ailments",
    genuineZones.get("mamool ja training grounds"),
  ],
  ["azure experiments", genuineZones.get("leujaoam sanctum")],
  ["a feast for gnats", genuineZones.get("ghoyu's reverie")],
  ["a manifest problem", genuineZones.get("fort karugo-narugo [s]")],
  ["a nation on the brink", genuineZones.get("everbloom hollow")],
  ["bellerophon's bliss", genuineZones.get("ilrusi atoll")],
  ["bellerophon's bliss|bellerophon's bliss", genuineZones.get("ilrusi atoll")],
  ["besieged", genuineZones.get("al zahbi")],
  ["better than one", genuineZones.get("lebros cavern")],
  ["better than one|better than one", genuineZones.get("lebros cavern")],
  ["blitzkrieg", genuineZones.get("mamool ja training grounds")],
  ["blitzkrieg|blitzkrieg", genuineZones.get("mamool ja training grounds")],
  ["bloody rondo|bloody rondo", genuineZones.get("leujaoam sanctum")],
  ["boyahda tree", genuineZones.get("the boyahda tree")],
  ["brave dawn i (bastok)", genuineZones.get("ruhotz silvermines")],
  ["brave dawn ii (b)", genuineZones.get("ruhotz silvermines")],
  ["brave dawn iii (bastok)", genuineZones.get("ruhotz silvermines")],
  ["brave dawn i (san d'oria)", genuineZones.get("everbloom hollow")],
  ["brave dawn iii (san d'oria)", genuineZones.get("everbloom hollow")],
  ["brave dawn ii (s)", genuineZones.get("everbloom hollow")],
  ["brave dawn ii [s]", genuineZones.get("everbloom hollow")],
  ["brave dawn i (windurst)", genuineZones.get("ghoyu's reverie")],
  ["brave dawn ii (w)", genuineZones.get("ghoyu's reverie")],
  ["brave dawn iii (windurst)", genuineZones.get("ghoyu's reverie")],
  ["breaking morale", genuineZones.get("mamool ja training grounds")],
  ["brunhilde's chamber", genuineZones.get("hazhalm testing grounds")],
  ["celestial nexus", genuineZones.get("the celestial nexus")],
  ["central apollyon", genuineZones.get("apollyon")],
  ["central temenos - basement 1", genuineZones.get("temenos")],
  ["central temenos - 1st floor", genuineZones.get("temenos")],
  ["central temenos - 2nd floor", genuineZones.get("temenos")],
  ["central temenos - 3rd floor", genuineZones.get("temenos")],
  ["central temenos - 4th floor", genuineZones.get("temenos")],
  ["crawler's nest", genuineZones.get("crawlers' nest")],
  ["cs apollyon", genuineZones.get("apollyon")],
  ["defuse the threat", genuineZones.get("periqia")],
  ["demolition duty", genuineZones.get("ilrusi atoll")],
  ["demolition duty|demolition duty", genuineZones.get("ilrusi atoll")],
  ["deserter", genuineZones.get("ilrusi atoll")],
  ["deserter|deserter", genuineZones.get("ilrusi atoll")],
  ["desperately seeking cephalopods", genuineZones.get("ilrusi atoll")],
  [
    "desperately seeking cephalopods|desperately seeking cephalopods",
    genuineZones.get("ilrusi atoll"),
  ],
  ["divine interference", genuineZones.get("alzadaal undersea ruins")],
  ["egg conservation|egg conservation", genuineZones.get("lebros cavern")],
  ["eldieme necropolis", genuineZones.get("the eldieme necropolis")],
  ["escort professor chanoix", genuineZones.get("leujaoam sanctum")],
  [
    "escort professor chanoix|escort professor chanoix",
    genuineZones.get("leujaoam sanctum"),
  ],
  ["evade and escape", genuineZones.get("lebros cavern")],
  ["excavation duty", genuineZones.get("lebros cavern")],
  ["excavation duty|excavation duty", genuineZones.get("lebros cavern")],
  [
    "garrison/beaucedine glacier|garrison",
    genuineZones.get("beaucedine glacier"),
  ],
  ["extermination|extermination", genuineZones.get("ilrusi atoll")],
  ["riverne - site b01", genuineZones.get("riverne - site #b01")],
  ["forging a new myth", genuineZones.get("nyzul isle")],
  ["gerhilde's chamber", genuineZones.get("hazhalm testing grounds")],
  ["golden salvage", genuineZones.get("ilrusi atoll")],
  ["golden salvage|golden salvage", genuineZones.get("ilrusi atoll")],
  ["granite rose i (bastok)", genuineZones.get("ruhotz silvermines")],
  ["granite rose ii (bastok)", genuineZones.get("ruhotz silvermines")],
  ["granite rose i (san d'oria)", genuineZones.get("everbloom hollow")],
  ["granite rose ii (san d'oria)", genuineZones.get("everbloom hollow")],
  ["granite rose i (windurst)", genuineZones.get("ghoyu's reverie")],
  ["granite rose ii (windurst)", genuineZones.get("ghoyu's reverie")],
  ["grimgerde's chamber", genuineZones.get("hazhalm testing grounds")],
  ["helmwige's chamber", genuineZones.get("hazhalm testing grounds")],
  ["honor under fire", genuineZones.get("vunkerl inlet [s]")],
  ["imperial agent rescue", genuineZones.get("mamool ja training grounds")],
  ["imperial code", genuineZones.get("leujaoam sanctum")],
  ["imperial code|imperial code", genuineZones.get("leujaoam sanctum")],
  ["in a haze of glory", genuineZones.get("ghoyu's reverie")],
  ["jazaraat's headstone", genuineZones.get("caedarva mire")],
  ["lamia no.13", genuineZones.get("ilrusi atoll")],
  ["lamia no.13 (mission)|lamia no.13", genuineZones.get("ilrusi atoll")],
  [
    "leujaoam cleansing|leujaoam cleansing",
    genuineZones.get("leujaoam sanctum"),
  ],
  ["lebros supplies", genuineZones.get("lebros cavern")],
  ["light in the darkness", genuineZones.get("pashhow marshlands [s]")],
  ["lost and found", genuineZones.get("ilrusi atoll")],
  ["lost and found|lost and found", genuineZones.get("ilrusi atoll")],
  ["mamook incursion", genuineZones.get("mamook")],
  ["marids in the mist", genuineZones.get("mamool ja training grounds")],
  ["mine shaft|mine shaft #2716", genuineZones.get("mine shaft #2716")],
  ["ne apollyon", genuineZones.get("apollyon")],
  ["nw apollyon", genuineZones.get("apollyon")],
  ["nyzul isle|nyzul isle", genuineZones.get("nyzul isle")],
  ["nyzul isle investigation", genuineZones.get("nyzul isle")],
  ["nyzul isle |nyzul isle", genuineZones.get("nyzul isle")],
  ["nyzul isle - nashmeira's plea", genuineZones.get("nyzul isle")],
  ["odin's chamber", genuineZones.get("hazhalm testing grounds")],
  ["operation: black pearl", genuineZones.get("lebros cavern")],
  ["operation: snake eyes", genuineZones.get("periqia")],
  ["operation: snake eyes|operation: snake eyes", genuineZones.get("periqia")],
  ["orichalcum survey", genuineZones.get("leujaoam sanctum")],
  ["ortlinde's chamber", genuineZones.get("hazhalm testing grounds")],
  ["ouryu cometh", genuineZones.get("riverne - site #a01")], // check this - this might be monarch linn
  ["pit spider i (bastok)", genuineZones.get("ruhotz silvermines")],
  ["pit spider ii (bastok)", genuineZones.get("ruhotz silvermines")],
  ["pit spider iii (bastok)", genuineZones.get("ruhotz silvermines")],
  ["pit spider i (san d'oria)", genuineZones.get("everbloom hollow")],
  ["pit spider ii (san d'oria)", genuineZones.get("everbloom hollow")],
  ["pit spider iii (san d'oria)", genuineZones.get("everbloom hollow")],
  ["pit spider i (windurst)", genuineZones.get("ghoyu's reverie")],
  ["pit spider ii (windurst)", genuineZones.get("ghoyu's reverie")],
  ["pit spider iii (windurst)", genuineZones.get("ghoyu's reverie")],
  ["preemptive strike", genuineZones.get("mamool ja training grounds")],
  [
    "preemptive strike|preemptive strike",
    genuineZones.get("mamool ja training grounds"),
  ],
  ["red versus blue|red vs blue", genuineZones.get("leujaoam sanctum")],
  ["requiem (mission)|requiem", genuineZones.get("periqia")],
  ["riverne - site a01", genuineZones.get("riverne - site #a01")],
  ["face of the future", genuineZones.get("yughott grotto")],
  ["rossweisse's chamber", genuineZones.get("hazhalm testing grounds")],
  ["royal painter escort", genuineZones.get("arrapago reef")],
  ["sagelord elimination", genuineZones.get("mamool ja training grounds")],
  [
    "sagelord elimination|sagelord elimination",
    genuineZones.get("mamool ja training grounds"),
  ],
  ["saintly invitation|saintly invitation", genuineZones.get("balga's dais")],
  ["saintly invitation", genuineZones.get("balga's dais")],
  ["sanctuary of zi'tah", genuineZones.get("the sanctuary of zi'tah")],
  ["saving private ryaaf", genuineZones.get("periqia")],
  ["schwertleite's chamber", genuineZones.get("hazhalm testing grounds")],
  ["scouting the ashu talif", genuineZones.get("arrapago reef")],
  ["seagull grounded", genuineZones.get("periqia")],
  ["seagull grounded|seagull grounded", genuineZones.get("periqia")],
  ["se apollyon", genuineZones.get("apollyon")],
  ["shanarha grass conservation", genuineZones.get("leujaoam sanctum")],
  [
    "ship bound for mhaura|ferry between mhaura & selbina",
    genuineZones.get("ship bound for mhaura"),
  ],
  ["shooting down the baron", genuineZones.get("periqia")],
  ["shrine of ru'avitau", genuineZones.get("the shrine of ru'avitau")],
  ["siegemaster assassination", genuineZones.get("lebros cavern")],
  ["siegrune's chamber", genuineZones.get("hazhalm testing grounds")],
  ["sins of the mothers", genuineZones.get("ghoyu's reverie")],
  ["stop the bloodshed", genuineZones.get("periqia")],
  ["storms of fate", genuineZones.get("riverne - site #b01")], // check this - this might be monarch linn
  ["supplies recovery", genuineZones.get("leujaoam sanctum")],
  ["sw apollyon", genuineZones.get("apollyon")],
  ["targeting the captain", genuineZones.get("arrapago reef")],
  ["temenos - eastern tower", genuineZones.get("temenos")],
  ["temenos - northern tower", genuineZones.get("temenos")],
  ["temenos - western tower", genuineZones.get("temenos")],
  ["the blood-bathed crown", genuineZones.get("castle oztroja [s]")],
  ["the double agent", genuineZones.get("mamool ja training grounds")],
  ["the gathering storm", genuineZones.get("mamool ja training grounds")],
  ["the price is right|the price is right", genuineZones.get("periqia")],
  ["the rider cometh", genuineZones.get("hazhalm testing grounds")],
  [
    "the savage|promathia mission 4-2: the savage",
    genuineZones.get("monarch linn"),
  ],
  [
    "the susanoo shuffle|the susanoo shuffle",
    genuineZones.get("mamool ja training grounds"),
  ],
  ["the wyrmking descends", genuineZones.get("riverne - site #b01")], // check this - this might be monarch linn
  ["troll fugitives|troll fugitives", genuineZones.get("lebros cavern")],
  ["under observation", genuineZones.get("horlais peak")],
  ["wake the puppet", genuineZones.get("periqia")],
  ["waltraute's chamber", genuineZones.get("hazhalm testing grounds")],
  ["wamoura farm raid|wamoura farm raid", genuineZones.get("lebros cavern")],
  ["xarcabard | xarcabard", genuineZones.get("xarcabard")],
]);

const invalidZones = new Map([
  ["annm", -1],
  ["archaic rampart", -1],
  ["bard", -1],
  ["beastmaster", -1],
  ["black mage", -1],
  ["dark knight", -1],
  ["gigas's bat", -1],
  ["gigas's leech", -1],
  ["gigas's sheep", -1],
  ["gigas's spider", -1],
  ["gigas's tiger", -1],
  ["goblin's bat", -1],
  ["goblin's bats", -1],
  ["goblin's bee", -1],
  ["goblin's beetle", -1],
  ["goblin's dragonfly", -1],
  ["goblin's leech", -1],
  ["goblin's ogrefly", -1],
  ["goblin's rabbit", -1],
  ["goblin's spider", -1],
  ["goblin's tiger", -1],
  ["hunt registry", -1],
  ["lamia exon", -1],
  ["mamool ja chamberlain", -1],
  ["monk", -1],
  ["ninja", -1],
  ["paladin", -1],
  ["pallas's tiger", -1],
  ["psycheflayer", -1],
  ["ranger", -1],
  ["reactionary rampart|rampart", -1],
  ["red mage", -1],
  ["samurai", -1],
  ["veridical conflux 1", -1],
  ["veridical conflux 2", -1],
  ["veridical conflux 5", -1],
  ["warrior", -1],
  ["white mage", -1],
  ["woodtroll elite guard", -1],
  ["xolotl", -1],
  ["zone", -1],
]);

export const zoneIDs = new Map([
  ...genuineZones,
  ...aliasZones,
  ...invalidZones,
]);

export const zoneNames = new Map<number, string>();
genuineZones.forEach((zoneID, zoneName) => zoneNames.set(zoneID, zoneName));
